### ISSUE TITLE
Error while processing CSV file

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#26]
We are getting following error while processing CSV. 

Probably we have to check whether locality is empty before calling title() on it.

`09/17/2016 06:13:19 PM WARNING: Geocode API failure for : '2nd Floor, Shop No.7, Siddhivinayak Estate Amraiwadi, Ahmedabad, 560040, India'

09/17/2016 06:13:20 PM WARNING: Trying by adding name failed for: '2nd Floor, Shop No.7, Siddhivinayak Estate Amraiwadi, Ahmedabad, 560040, India'hence taking city geocodes

Traceback (most recent call last):
  File "geocodertest.py", line 187, in <module>
    f.process()
  File "geocodertest.py", line 47, in process
    self._addGeocoding();
  File "geocodertest.py", line 72, in _addGeocoding
    row["Locality"] = row["Locality"].title()
AttributeError: 'NoneType' object has no attribute 'title'
1
./output/processed_sample.csv -> updated_sample.csv
2
./output/processed_small.csv -> updated_small.csv`

**Comment by rohitmanglik** [comment]
Verified the fix
