### ISSUE TITLE
Error while saving CSV File

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#29]
09/18/2016 04:47:34 AM ERROR: Something awful happened when processing result.csv
Traceback (most recent call last):
  File "geocodertest.py", line 224, in _writeCSV
    writer.writerow(row)
  File "/usr/lib/python2.7/csv.py", line 152, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "/usr/lib/python2.7/csv.py", line 148, in _dict_to_list
    + ", ".join([repr(x) for x in wrong_fields]))
ValueError: dict contains fields not in fieldnames: None
***Successfully processed 2 files.***

**Comment by shashwat-vik** [comment]
Described the cause of this error in the commit's comment.

**Comment by rohitmanglik** [comment]
Verified fix.
