### ISSUE TITLE
Facebook Graph API

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#36]
Facebook has a lot of information about places in India. Sometimes that information is at par with that of Google. e.g. we might not share photo with Google+ but we do it on FB. 

Through this we can also get Facebook Page URL, owner's information etc.

We certainly have to create a facebook app to fetch that information.

**Comment by gupta-shantanu** [comment]
8f334d3 searches facebook page, description and cover photo from GraphAPI and also attempts to repair voids if possible. However, data obtained from facebook is quite sparse because most of institutions are not listed on facebook. It works well for prominent institutes.

**Comment by rohitmanglik** [comment]
Latest log:
	Details:66 Facebook Link:282 Cover:204
	Website:67 Pincode:0 Address:31 Images:234 Verified 0/282 Phone:220 Emails:0

Why Emails are zero? Is it in every case? If yes, why are we considering it at all?

**Comment by rohitmanglik** [comment]
@shashwat-vik repeat autocomplete patter or create a new one over here as well.

**Comment by rohitmanglik** [comment]
Got following error in sample_big.csv

	`0%10/06/2016 06:48:49 PM ERROR: Error loading information from facebook for Perfect Career Education
	Traceback (most recent call last):
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 177, in processAll
		node = self.searchPlace(row)
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 45, in searchPlace
		if unicode(pin) == unicode(place['location']['zip'])  and unicode(pin):
	KeyError: 'zip'
	0%10/06/2016 06:48:50 PM ERROR: Error loading information from facebook for Career Point
	Traceback (most recent call last):
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 177, in processAll
		node = self.searchPlace(row)
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 45, in searchPlace
		if unicode(pin) == unicode(place['location']['zip'])  and unicode(pin):
	KeyError: 'zip'
	0%10/06/2016 06:48:50 PM ERROR: Error loading information from facebook for Precept
	Traceback (most recent call last):
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 177, in processAll
		node = self.searchPlace(row)
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 45, in searchPlace
		if unicode(pin) == unicode(place['location']['zip'])  and unicode(pin):
	KeyError: 'zip'
	1%10/06/2016 06:48:51 PM ERROR: Error loading information from facebook for J.D. Classes
	Traceback (most recent call last):
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 177, in processAll
		node = self.searchPlace(row)
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 45, in searchPlace
		if unicode(pin) == unicode(place['location']['zip'])  and unicode(pin):
	KeyError: 'zip'
	10/06/2016 06:48:51 PM ERROR: Error loading information from facebook for I.C.R. Education Services
	Traceback (most recent call last):
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 177, in processAll
		node = self.searchPlace(row)
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 45, in searchPlace
		if unicode(pin) == unicode(place['location']['zip'])  and unicode(pin):
	KeyError: 'zip'
	1%10/06/2016 06:48:52 PM ERROR: Error loading information from facebook for Navigator Solutions
	Traceback (most recent call last):
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 177, in processAll
		node = self.searchPlace(row)
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 45, in searchPlace
		if unicode(pin) == unicode(place['location']['zip'])  and unicode(pin):
	KeyError: 'zip'
	3%10/06/2016 06:48:56 PM ERROR: Error loading information from facebook for The English Channel
	Traceback (most recent call last):
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 177, in processAll
		node = self.searchPlace(row)
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 45, in searchPlace
		if unicode(pin) == unicode(place['location']['zip'])  and unicode(pin):
	KeyError: 'zip'
	4%10/06/2016 06:49:00 PM ERROR: Error loading information from facebook for Foresight School
	Traceback (most recent call last):
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 177, in processAll
		node = self.searchPlace(row)
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 45, in searchPlace
		if unicode(pin) == unicode(place['location']['zip'])  and unicode(pin):
	KeyError: 'zip'
	10/06/2016 06:49:00 PM ERROR: Error loading information from facebook for Prosper Overseas
	Traceback (most recent call last):
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 177, in processAll
		node = self.searchPlace(row)
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 45, in searchPlace
		if unicode(pin) == unicode(place['location']['zip'])  and unicode(pin):
	KeyError: 'zip'
	10/06/2016 06:49:00 PM ERROR: Error loading information from facebook for ICES - Innovative & Creative Education Solution
	Traceback (most recent call last):
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 177, in processAll
		node = self.searchPlace(row)
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 45, in searchPlace
		if unicode(pin) == unicode(place['location']['zip'])  and unicode(pin):
	KeyError: 'zip'
	5%10/06/2016 06:49:01 PM ERROR: Error loading information from facebook for IMS Learning Resources Pvt. Ltd.
	Traceback (most recent call last):
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 177, in processAll
		node = self.searchPlace(row)
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 45, in searchPlace
		if unicode(pin) == unicode(place['location']['zip'])  and unicode(pin):
	KeyError: 'zip'
	5%10/06/2016 06:49:01 PM ERROR: Error loading information from facebook for R. Patel Institute
	Traceback (most recent call last):
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 177, in processAll
		node = self.searchPlace(row)
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 45, in searchPlace
		if unicode(pin) == unicode(place['location']['zip'])  and unicode(pin):
	KeyError: 'zip'
	5%10/06/2016 06:49:01 PM ERROR: Error loading information from facebook for Endeavor Careers Pvt. Ltd.
	Traceback (most recent call last):
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 177, in processAll
		node = self.searchPlace(row)
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 45, in searchPlace
		if unicode(pin) == unicode(place['location']['zip'])  and unicode(pin):
	KeyError: 'zip'
	6%10/06/2016 06:49:02 PM ERROR: Error loading information from facebook for Garuda Education
	Traceback (most recent call last):
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 177, in processAll
		node = self.searchPlace(row)
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 45, in searchPlace
		if unicode(pin) == unicode(place['location']['zip'])  and unicode(pin):
	KeyError: 'zip'
	6%10/06/2016 06:49:03 PM ERROR: Error loading information from facebook for Concept Education
	Traceback (most recent call last):
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 177, in processAll
		node = self.searchPlace(row)
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 45, in searchPlace
		if unicode(pin) == unicode(place['location']['zip'])  and unicode(pin):
	KeyError: 'zip'
	7%10/06/2016 06:49:03 PM ERROR: Error loading information from facebook for Royal Institute
	Traceback (most recent call last):
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 177, in processAll
		node = self.searchPlace(row)
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 45, in searchPlace
		if unicode(pin) == unicode(place['location']['zip'])  and unicode(pin):
	KeyError: 'zip'
	7%10/06/2016 06:49:03 PM ERROR: Error loading information from facebook for Genieus Academy
	Traceback (most recent call last):
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 177, in processAll
		node = self.searchPlace(row)
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 45, in searchPlace
		if unicode(pin) == unicode(place['location']['zip'])  and unicode(pin):`

**Comment by rohitmanglik** [comment]
Regarding EMails:

It should first check whether value in claim_email already set. If the value in claim_email is empty, insert value in claim_email, else insert it in Mail2.

Currently value is being put in Mail2 irrespective of the value in claim_email.

**Comment by rohitmanglik** [comment]
In sample.csv, shiksha- The Commerce Classes has same EMail address in claim_email and Mail2.

**Comment by rohitmanglik** [comment]
@gupta-shantanu @shubhiD any update on above comment? 

(In sample.csv, shiksha- The Commerce Classes has same EMail address in claim_email and Mail2.)

**Comment by shashwat-vik** [comment]
Overlook the commit 70f3c4a063be733608cd565190c3ae10f5fc8580
That on my local branch.

**Comment by rohitmanglik** [comment]
Current status: waiting for final analysis from @shashwat-vik

**Comment by shashwat-vik** [comment]
You can't get the individual people's review for a page using the API.
That would require page token for that page, or the user token who is admin of that page.
And that's true for the public pages as well.

However other info's that you can get hold by the App Access token we are using are:

1. Page aggregate rating
2. Total count of people visited
3. Total count of likes
4. Working hours
5. Albums with photos
6. Videos	
7. Top 100 Posts on the pages

These are the main ones, rest would be extras that most institutes wont care to fill up.

**Comment by rohitmanglik** [comment]
@shashwat-vik Please fetch following details and save in separate columns in csv file.

Working hours
Albums with photos
Videos
Top 100 Posts on the pages

@shubhiD Please take it forward from above 4 columns and consolidate those values to existing fields.

**Comment by gupta-shantanu** [comment]
@shashwat-vik  Is this the format for final output of working ours:
```a:7:{i:0;a:3:{s:17:"listing_time_from";s:5:"10 AM";s:11:"listing_day";s:6:"MONDAY";s:15:"listing_time_to";s:4:"7 PM";}i:1;a:3:{s:17:"listing_time_from";s:5:"10 AM";s:11:"listing_day";s:7:"TUESDAY";s:15:"listing_time_to";s:4:"7 PM";}i:2;a:3:{s:17:"listing_time_from";s:5:"10 AM";s:11:"listing_day";s:6:"FRIDAY";s:15:"listing_time_to";s:4:"7 PM";}i:3;a:3:{s:17:"listing_time_from";s:5:"10 AM";s:11:"listing_day";s:9:"WEDNESDAY";s:15:"listing_time_to";s:4:"7 PM";}i:4;a:3:{s:17:"listing_time_from";s:5:"10 AM";s:11:"listing_day";s:8:"THURSDAY";s:15:"listing_time_to";s:4:"7 PM";}i:5;a:3:{s:17:"listing_time_from";s:5:"10 AM";s:11:"listing_day";s:6:"SUNDAY";s:15:"listing_time_to";s:4:"3 PM";}i:6;a:3:{s:17:"listing_time_from";s:5:"10 AM";s:11:"listing_day";s:8:"SATURDAY";s:15:"listing_time_to";s:4:"7 PM";}}```
I am working on converting listing hours dictionary returned by fb to this format.

**Comment by gupta-shantanu** [comment]
@shashwat-vik I am not able to fetch hours from [facebook api](https://developers.facebook.com/tools/explorer/?method=GET&path=607618802745506%3Ffield%3Dhours&version=v2.8), while it's listed there on actual page. Is there something extra that needs to be done? Can you send me a sample 'hours' dictionary returned by fb Graph API asap?

**Comment by shashwat-vik** [comment]
@gupta-shantanu  Yes this is the final format for working hours.

Convert and merge data from column **'fb_workingHours'** to **'Working Hours'**, only if it was empty.
If **'Working Hours'** already got updated by **googleAutocomplete** don't merge.

@rohitmanglik  Please confirm this too.

**Comment by shubhiD** [comment]
@gupta-shantanu if you are parsing the working hours than make a format like this:

[{'listing_time_from': '3 PM', 'listing_day': 'MONDAY', 'listing_time_to': '7.30 PM'}, {'listing_time_from': '3 PM', 'listing_day': 'TUESDAY', 'listing_time_to': '7.30 PM'}, {'listing_time_from': '3 PM', 'listing_day': 'WEDNESDAY', 'listing_time_to': '7.30 PM'}, {'listing_time_from': '3 PM', 'listing_day': 'THURSDAY', 'listing_time_to': '7.30 PM'}, {'listing_time_from': '3 PM', 'listing_day': 'FRIDAY', 'listing_time_to': '7.30 PM'}, {'listing_time_from': '3 PM', 'listing_day': 'SATURDAY', 'listing_time_to': '7.30 PM'}, {'listing_custom': 'closed', 'listing_day': 'SUNDAY'}]

for institutes that are closed on specific day have 'listing_custom':'closed' like in sunday above
after that just pass this result in phpserialize.serialize() you will have the output you commented

import phpserialize in your code too

**Comment by rohitmanglik** [comment]
I concur. You can also refer #6 for more details.

Just a small change: You should not say "7 PM" but "07:00 PM"

**Comment by shashwat-vik** [comment]
@gupta-shantanu . Do the merging of FB Working Hour row inside the function **'_mergeData()'** defined under fbGraph.py

**Comment by shashwat-vik** [comment]
Checked on all input files, after the recent commits. No errors in Graph API module.
Closing the issue.
