### ISSUE TITLE
Test with updated sample dataset and rectify errors.

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#48]

**Comment by rohitmanglik** [comment]
Running all the test cases!

**Comment by rohitmanglik** [comment]
@gupta-shantanu  While processing scrap_visakhapatnam.csv, we are getting following error

	No of place id ->132
	Permanently closed is  M N R School
	Permanently closed is  Nazareth Play School
	Permanently closed is  M N R School
	viewports for  14
	ADDING GEOCODES...
	Processed 50 rows.
	Processed 100 rows.
	Processed 150 rows.
	Total precise entries: 145 out of 168
	Fetching info from FB Graph
	17%10/02/2016 06:21:10 PM ERROR: Error loading information from facebook for Kotak Salesian School
	Traceback (most recent call last):
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 185, in processAll
		phone += self._addPhone(row,node)
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 122, in _addPhone
		ph = map(UTF8,str(node['phone']).split(','))
	UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 7: ordinal not in range(128)
	56%10/02/2016 06:21:43 PM ERROR: Error loading information from facebook for Kotak Salesian School
	Traceback (most recent call last):
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 185, in processAll
		phone += self._addPhone(row,node)
	  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 122, in _addPhone
		ph = map(UTF8,str(node['phone']).split(','))
	UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 7: ordinal not in range(128)
	100%
	New Info Added from Facebook

**Comment by rohitmanglik** [comment]
Manually verified the fix. Closing the issue.
