### ISSUE TITLE
Error in scrap_visakhapatnam.csv

### ISSUE THREAD

**Issue by shashwat-vik** [rohitmanglik/scrap-preprocessor#63]
```
Fetching info from FB Graph

New Info Added from Facebook
Details:36 Facebook Link:79 Cover:63 
Website:4 Pincode:4 Address:24 Images:77 Verified 0/79 Phone:69 Emails:43
Traceback (most recent call last):
  File "geocodertest.py", line 246, in <module>
    f.process()
  File "geocodertest.py", line 71, in process
    self.mobiles.processAll(self.rows)
  File "/home/bitnami/shashwat/testing/scrap-preprocessor/mobileAPI.py", line 110, in processAll
    self.checkNo(rows)
  File "/home/bitnami/shashwat/testing/scrap-preprocessor/mobileAPI.py", line 62, in checkNo
    y=(filter(lambda x: not x.isalpha(),unicode(row['Phone'+str(i)])).strip().replace(' ',''))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5: ordinal not in range(128)
```

**Comment by pinakinathc** [comment]
@shashwat-vik 
i tried to execute geocodertest.py by commenting other functions like 
self.autoComp.main(self.rows) #line 67
self._addGeocoding() #line 68
this gave no errors.

So maybe that new data is being fetched from fbGraph.py and those new entries are showing these errors??

**Comment by rohitmanglik** [comment]
Yes, that's what you have to debug right? FBGraph is returning some string and that has some encoding issue. mobileAPI should have handled that encoding thing gracefully. 

You are supposed to fix encoding issue in mobileAPI.
